### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by gavra2001** [xan1242/hp2wsfix#1]
My game crashes when i try to launch it with this exception error
![Untitled](https://user-images.githubusercontent.com/51299899/72224983-70a26b80-3580-11ea-8bcc-252378c69c52.png)
I really have no clue on how to increase the memory allocations with addresses i tried and it didnt work, i do have a mod, but only one

**Comment by xan1242** [comment]
EIP ends up at an instruction which doesn't exist, at 0053B910 it should push the MB_CHARACTER string for the memory printout.

I'll investigate this a bit further. It indeed seems to be an issue with memory allocations but it's unrelated to the numbers in the ini file themselves, so reconfiguring those numbers can't and shouldn't fix this issue you're having.

**Comment by xan1242** [comment]
One more thing - I'd need to know exactly what kind of the other mod you have installed.

Car mods are generally unstable in this game (as the game is unstable stock anyways - stock Corvette crash my game)

**Comment by xan1242** [comment]
I've deleted my previous comments - this is a version issue.

You have the version 240. This was exclusively developed with 242 in mind. You should update your game to the latest version for it to work.

I'll update the README to include such information. I haven't foreseen this issue since I half-expected everybody to have the last version.

**Comment by gavra2001** [comment]
> I've deleted my previous comments - this is a version issue.
> 
> You have the version 240. This was exclusively developed with 242 in mind. You should update your game to the latest version for it to work.
> 
> I'll update the README to include such information. I haven't foreseen this issue since I half-expected everybody to have the last version.

thanks, just updated my game version and it works just fine now 😄
