### ISSUE TITLE
Getting 'exception error' when starting the game

### ISSUE THREAD

**Issue by peter099** [xan1242/hp2wsfix#15]
I have NFS 2 Hot Pursuit installed on Windows 10 Pro and the resolution of my laptop screen is 1920x1080. I have set the comparability mode for NFSHP2.exe to Windows XP. I downloaded the ReleasePack.zip for Windows XP compatibility release and copy the files to the game root directory. But when i start the game i get this error:

```
---------------------------
Need For Speed Hot Pursuit 2 (exception error)
---------------------------
(Hit Cntrl-C to copy this info to the clipboard)

The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 

 Version: 240
 EIP = 0x0053B912
 ESP = 0x0019FD9C  EBP = 0x0019FDC4
 EAX = 0x0766D320
 EBX = 0x00000000
 ECX = 0x0766D3A0
 EDX = 0x0766D34C
 ESI = 0xFFFFFFFF  EDI = 0x070D72A0
---------------------------
OK   
---------------------------
```

**Comment by xan1242** [comment]
Problem is during printing of the memory status.

Test 2 things:

1. Game without the WS fix
2. With WS fix but remove HP2WSFix.ini and rename HP2WSFix_LowMem.ini to HP2WSFix.ini

If it works with 2. then maybe you don't have enough RAM to run the game (or maybe the EXE needs patching with https://ntcore.com/?page_id=371 )

**Comment by xan1242** [comment]
Version: 240 is your problem

Please fulfill all [requirements](https://github.com/xan1242/hp2wsfix#requirements-for-the-release-binaries) before running HP2WSFix.

**Comment by other-code** [comment]
This issue is also present on the latest patch for the game. Someone edited [PCGW](https://www.pcgamingwiki.com/wiki/Need_for_Speed:_Hot_Pursuit_2#Issues_fixed) to say that you need to copy some content from the original game CD, but this didn't fix it for me. What did ultimately fix it was replacing the WSFix render hook (d3d8.dll) with DGVoodoo, now the game starts fine. I'm not sure if I'm missing out on any special fixes from WSFix though... hopefully this can be looked into.

```
---------------------------
Need For Speed Hot Pursuit 2 (exception error)
---------------------------
(Hit Cntrl-C to copy this info to the clipboard)

The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 

 Version: 242
 EIP = 0x6256B32F
 ESP = 0x0019F158  EBP = 0x04000000
 EAX = 0x27B18035
 EBX = 0x00000001
 ECX = 0x00004954
 EDX = 0x30BCA740
 ESI = 0x30BCEA08  EDI = 0x00004950
---------------------------
OK   
---------------------------
```

**Comment by Vandino86** [comment]
> This issue is also present on the latest patch for the game. Someone edited [PCGW](https://www.pcgamingwiki.com/wiki/Need_for_Speed:_Hot_Pursuit_2#Issues_fixed) to say that you need to copy some content from the original game CD, but this didn't fix it for me. What did ultimately fix it was replacing the WSFix render hook (d3d8.dll) with DGVoodoo, now the game starts fine. I'm not sure if I'm missing out on any special fixes from WSFix though... hopefully this can be looked into.
> 
> ```
> ---------------------------
> Need For Speed Hot Pursuit 2 (exception error)
> ---------------------------
> (Hit Cntrl-C to copy this info to the clipboard)
> 
> The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 
> 
>  Version: 242
>  EIP = 0x6256B32F
>  ESP = 0x0019F158  EBP = 0x04000000
>  EAX = 0x27B18035
>  EBX = 0x00000001
>  ECX = 0x00004954
>  EDX = 0x30BCA740
>  ESI = 0x30BCEA08  EDI = 0x00004950
> ---------------------------
> OK   
> ---------------------------
> ```

I pretty much have this same issue, so I think it should be reopened. I got nothing against dgVoodoo, but I really wish I could use the widescreen fix instead like I could with UG, UG2, and MW2005. I know the widescreen fixes for those are made by a different author (ThirteenAG), but still.

Here's what my error looks like, btw:

```
---------------------------
Need For Speed Hot Pursuit 2 (exception error)
---------------------------
(Hit Cntrl-C to copy this info to the clipboard)

The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 

 Version: 242
 EIP = 0x642DE1FF
 ESP = 0x0019F878  EBP = 0x04000000
 EAX = 0xBEEFBEEF
 EBX = 0x00000001
 ECX = 0x0000519C
 EDX = 0x2C746BC0
 ESI = 0x2C74B6D0  EDI = 0x00005198
---------------------------
OK   
---------------------------
```

**Comment by Maxkatsur** [comment]
> > This issue is also present on the latest patch for the game. Someone edited [PCGW](https://www.pcgamingwiki.com/wiki/Need_for_Speed:_Hot_Pursuit_2#Issues_fixed) to say that you need to copy some content from the original game CD, but this didn't fix it for me. What did ultimately fix it was replacing the WSFix render hook (d3d8.dll) with DGVoodoo, now the game starts fine. I'm not sure if I'm missing out on any special fixes from WSFix though... hopefully this can be looked into.
> > ```
> > ---------------------------
> > Need For Speed Hot Pursuit 2 (exception error)
> > ---------------------------
> > (Hit Cntrl-C to copy this info to the clipboard)
> > 
> > The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 
> > 
> >  Version: 242
> >  EIP = 0x6256B32F
> >  ESP = 0x0019F158  EBP = 0x04000000
> >  EAX = 0x27B18035
> >  EBX = 0x00000001
> >  ECX = 0x00004954
> >  EDX = 0x30BCA740
> >  ESI = 0x30BCEA08  EDI = 0x00004950
> > ---------------------------
> > OK   
> > ---------------------------
> > ```
> 
> I pretty much have this same issue, so I think it should be reopened. I got nothing against dgVoodoo, but I really wish I could use the widescreen fix instead like I could with UG, UG2, and MW2005. I know the widescreen fixes for those are made by a different author (ThirteenAG), but still.
> 
> Here's what my error looks like, btw:
> 
> ```
> ---------------------------
> Need For Speed Hot Pursuit 2 (exception error)
> ---------------------------
> (Hit Cntrl-C to copy this info to the clipboard)
> 
> The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 
> 
>  Version: 242
>  EIP = 0x642DE1FF
>  ESP = 0x0019F878  EBP = 0x04000000
>  EAX = 0xBEEFBEEF
>  EBX = 0x00000001
>  ECX = 0x0000519C
>  EDX = 0x2C746BC0
>  ESI = 0x2C74B6D0  EDI = 0x00005198
> ---------------------------
> OK   
> ---------------------------
> ```

Yeah, same too for me:
```
---------------------------
Need For Speed Hot Pursuit 2 (exception error)
---------------------------
(Hit Cntrl-C to copy this info to the clipboard)

The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 

 Version: 242
 EIP = 0x7728833A
 ESP = 0x0019F08C  EBP = 0x0019F22C
 EAX = 0x00C100C0
 EBX = 0x00C42A98
 ECX = 0x00000080
 EDX = 0x00000000
 ESI = 0x00000008  EDI = 0x00C10000
---------------------------
ОК   
---------------------------
```

Maybe this app and the patches are underprepared to run from `D:\Games\Need for Speed - Hot Pursuit 2` (I have only ONE SSD on my laptop, as the physical drive has two simultaneous virtual drives, `C: `and `D:`) safely, even with DirectPlay on. Not even DgVoodoo could prevent this exception error. We need some more further research on this issue, maybe the brand-new patch for this game can help.

**Comment by DelmorS** [comment]
> > > This issue is also present on the latest patch for the game. Someone edited [PCGW](https://www.pcgamingwiki.com/wiki/Need_for_Speed:_Hot_Pursuit_2#Issues_fixed) to say that you need to copy some content from the original game CD, but this didn't fix it for me. What did ultimately fix it was replacing the WSFix render hook (d3d8.dll) with DGVoodoo, now the game starts fine. I'm not sure if I'm missing out on any special fixes from WSFix though... hopefully this can be looked into.
> > > ```
> > > ---------------------------
> > > Need For Speed Hot Pursuit 2 (exception error)
> > > ---------------------------
> > > (Hit Cntrl-C to copy this info to the clipboard)
> > > 
> > > The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 
> > > 
> > >  Version: 242
> > >  EIP = 0x6256B32F
> > >  ESP = 0x0019F158  EBP = 0x04000000
> > >  EAX = 0x27B18035
> > >  EBX = 0x00000001
> > >  ECX = 0x00004954
> > >  EDX = 0x30BCA740
> > >  ESI = 0x30BCEA08  EDI = 0x00004950
> > > ---------------------------
> > > OK   
> > > ---------------------------
> > > ```
> > 
> > 
> > I pretty much have this same issue, so I think it should be reopened. I got nothing against dgVoodoo, but I really wish I could use the widescreen fix instead like I could with UG, UG2, and MW2005. I know the widescreen fixes for those are made by a different author (ThirteenAG), but still.
> > Here's what my error looks like, btw:
> > ```
> > ---------------------------
> > Need For Speed Hot Pursuit 2 (exception error)
> > ---------------------------
> > (Hit Cntrl-C to copy this info to the clipboard)
> > 
> > The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 
> > 
> >  Version: 242
> >  EIP = 0x642DE1FF
> >  ESP = 0x0019F878  EBP = 0x04000000
> >  EAX = 0xBEEFBEEF
> >  EBX = 0x00000001
> >  ECX = 0x0000519C
> >  EDX = 0x2C746BC0
> >  ESI = 0x2C74B6D0  EDI = 0x00005198
> > ---------------------------
> > OK   
> > ---------------------------
> > ```
> 
> Yeah, same too for me:
> 
> ```
> ---------------------------
> Need For Speed Hot Pursuit 2 (exception error)
> ---------------------------
> (Hit Cntrl-C to copy this info to the clipboard)
> 
> The thread attempted to read from or write to a virtual address for which it does not have the appropriate access. 
> 
>  Version: 242
>  EIP = 0x7728833A
>  ESP = 0x0019F08C  EBP = 0x0019F22C
>  EAX = 0x00C100C0
>  EBX = 0x00C42A98
>  ECX = 0x00000080
>  EDX = 0x00000000
>  ESI = 0x00000008  EDI = 0x00C10000
> ---------------------------
> ОК   
> ---------------------------
> ```
> 
> Maybe this app and the patches are underprepared to run from `D:\Games\Need for Speed - Hot Pursuit 2` (I have only ONE SSD on my laptop, as the physical drive has two simultaneous virtual drives, `C: `and `D:`) safely, even with DirectPlay on. Not even DgVoodoo could prevent this exception error. We need some more further research on this issue, maybe the brand-new patch for this game can help.

The same for me, can not run HP2 on Windows 11 with any combinations of fixes from PCGW. Tried: 
1) hp2wsfix
2) dgvoodoo
3) directinput fps fix
4) registry edit in order to disable old Games service
5) run game via Admin
6) Windowed mode, and setting resolutions from 800x600 to 1920x1080
Nothing helps, unfortunatelly. On virtual machine of Windows XP game is launching instantly, without any fixes at all.

**Comment by Aashrith0907** [comment]
i have downloaded the NFS hot pursuit 2(2002) on my intel laptop and no matter what i do, there is always a white screen making the map to race almost invisible.
