### ISSUE TITLE
Horizontally squished on 1366x768

### ISSUE THREAD

**Issue by parkerlreed** [xan1242/hp2wsfix#18]
i3-8145u (and the accompying iGPU). Windows 10

![image](https://user-images.githubusercontent.com/841440/151687754-51079bb4-7f9d-4740-861d-a5c96a7f508a.png)

**Comment by xan1242** [comment]
Hi, sorry for late reply, I'm just now able to see this.

Interesting how the aspect ratio calculations go wacky like this, I'll check it out with 1366x768 (and a device with that kind of a panel) but I do remember this running fine on a 1366x768 laptop.

**Comment by xan1242** [comment]
I can't seem to replicate the problem. To me it seems like you tried to use another widescreen fix along this one.

Please post your Cars\cameras.ini here. If it's modified, then that's the reason why you have the problem.

This one requires you to use stock files.

**Comment by parkerlreed** [comment]
As far as I'm aware that was completely stock. I have my own disc and applied the 242 patch. I've been unable to reproduce on other hardware since then, so it may be down to that specific laptop/iGPU combo. Sadly that was one I only had access to for a short time. Thanks for checking on it. Will close this out for now and revisit if I encounter this again.
